services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - bootstrap.memory_lock=true # reduce swap
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - net1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cat/health?h=status | grep -q green"]
      retries: 300
      interval: 2s
  fastapi:
    image: app
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    networks:
      - net1
    ports:
      - 8080:8080
    volumes:
      - .:/app

#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.15.3
#    container_name: kibana
#    environment:
#      SERVER_NAME: kibana
#      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
#    ports:
#      - 5601:5601
#    depends_on:
#      - elasticsearch
#    networks:
#      - net1

networks:
  net1:
    driver: bridge

volumes:
  esdata:
    driver: local